;; (require 'org)
;; (org-babel-load-file "~/.emacs.d/config.org")
(defun load-org-file (org-filename)
  (let ((el-filename (concat (file-name-sans-extension org-filename) ".el")))
    (if (and (file-exists-p el-filename)
             (file-newer-than-file-p el-filename org-filename))
        (load el-filename)
      (org-babel-load-file org-filename))))
(load-org-file "~/.emacs.d/config.org")
